apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCwCKQ0lrdze86+rqYvsSxBXcscN/FvuCTI458ET/2/C/kOQQNHp3mXPbcpwE9CyTc+eSWjCi1PSSopisBqLQ1+d97s+ipYHKnEwRumo3sURqRygETlyMUtbXdQs6Jqqv1I+2CqU05K5r716WT0vGzHOihURq4ILbBtWTpb+ljTKnhw3JaWA4vnDYogx8pUglP0SCkEy4unidnBfn5DlKe5DDDiCeKtBQfZYYMDaRq1UIjJ5sAwKQ2GOdIlBdAuNDm3fj+Ov3WwnEVGLpkOGjOOd29LKarx94h2eXps6aJVDDVjxzBpZdO6peq1Ma6GROzmqirWAn6WlNxViHmNoLI3IpMlVUVx4WgUyAWivOcKN+R3cPTq4UmO1IvJWRR8YbwIdt5nWcq2kD4x5phQ3JhEh+XEgn4RPXXmF+uslTfpMxdRbXIbfzSJlleMmJWeackM5kySPr6TC7UC3bIadrbZhKtxID29agBqZAEZ7Syd1jOstAb6P7mSExJno3Y+GKeb1UjQ8ZhWITHl8QGELUpCemb55A15E/eOUs3sudZw4bovWboO4BDc2xfoBoJC1oJtFA0uGZYR8CvDIkGie8oEUqAFObYI0fIlWBTbQo2ARGYd3CvMylS2YcFVCRqCksWIv0hcBbGlrmvFPZUzkSVoqo9/VziTU5VoSKpRP1BRFcelxl/lwWhqELtaTjWupZx9XZCPdLQuCVlyTuxu/in7xJzqy0rR05DtUNaXQcy3lk/3cULh8pHC+coAkgBmuZ7o7g2T4J0mj0QFQijXNgV1FqbPKxihdAbcqLstlykKvxDUppLpUgXw4N64qKjSh5DCGd6YTMp7HWR61fecGnRf2XXk0dAdWtU0Fa9XwJjg4O5H693y1Z6FQWUwJpIPqy8Jrx+L+dknJEmaZZgXkih6Fxk=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

