apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBvCldeWgDkAN9mcDwyfFHcblP3DmnzzJ3CQoxDU5dqx8f5ZfzpCH/3uqh99Rq369W4XuGzGQGOlSSr1pc6FFefRFQc8Fg8+w/ZesVYFa05pL3yQS0WtXbDFqibobXyuG56nfPOL0Rs/JiwAlR3ouWvJVOMrB3cz0WygUJPMTZUrI5JMLQVEVD45g1modlSUhf7/gS9o1sKyygOhIxWwfo6qk71NYwVZAPO7sEgfRnSzNeJltX3B+xATEaJcGIXxFw4fm8Y9jBvhAkK+gG4UHGm4w3tw8swGW+bRojAb3mP4DrZh4GhTcMAlKzVjtpI3DzfB7BNYhFsNKtB4HgTyO9wbNJ1FyerruEP4AbM3BHaWdviYEkC/j0ZNXb618w8W/763Xcj0uV0XfHg5vRJiLKB72aMfhwFdwecNQPb730xnxeiXf13PGwEb36/Qxd/1zlK7NH4aRZ/9tITRekcOOijv11sFH4Mz8uJkWLFvaRsSRSl+vEvw1vdGxy/2wHcAHg/zZ96uetyzARp+3uKrR7b/+hR22qh+FRq4qdQEaHZCMYe71LkEJOLuh6ns8FsSAEna/8DQCsW0BhiXoP3fnd9DUc7n9AhkEQB1o20b6lgXugtqMR00EWlqQhaWOlv0IK7xVSNRyrzk+oQ8fLTPs0tRYXwnLDohPPWeRHuX59zUVgTms7eS02c+K78OkKKcBxT3jV6XpEBPGxuGsVN1oME8zRK73wX5Po5hPkKtRf3il/+bAaqo8Bi
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

