apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBqRuqxADZHvn5v/RiyLUudUA+m7IboRydtT6fQWTYHD+DCKKnTkIbiv2VAKqQHGj7MihUIiT2+fIaLlXqX2S08FY4B89F+HRUJfpETAxS/wk8ZUvjQCHZ8IClvu6RpyBfo25SqEtnbCdVXN+tPIfVHw0qaE11vZUDXrjnfONzRghma7Fnr2KUa7qo36m4T1glbi+dsTqYB+Guum/2wDNWb1o7PuCDP3ozIPTArKtv0shtJEua7ucrAyrM+daE1drnTxCF2vcEeRMPdFFehfeAHxEJXoSwTu1A/MfBmq6u9DdfLpEAkOiz2NBHSQgJynaY1VOUH1jlAUMsMYR49vAKcAgKPJw5XqQPz/QtCVvYqCyrISYfpyocJLYneMsB8QXtuKmJYJpUb6VdW/EgADpy0k5+1X3WJWTjKp+nx7vidb7wby0JBUyhw4b2CnXnwtb17YaPJOfrfTN64+mhUiC4w3HnrQE+5zqgnhS2hvnkzBbPUqH0OwFTE9U30z51o6qrWmxGP7FmyBfDyeh1w+E4g7BrFkMwB4VUNLW4ZgOzx6pjO00uGqDLcjE7T3Cy1w8wO5/MbNLO2arHVYaSbw7zzWavflZDgDdCW4dCfpAJZlY/naeJXpu68V1oDW8PPVSkORqdHtQ/bUXHsbm1ABiY6iTwepd3WoFtSJnPhPLL44TWLQ/T8FlNO1Y4SNh4awypV6v+QwPAKZMMX4EbyqnZLgh8UIlb0pa/JeiyEIfoGI0CzVrbcoOpz
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

