apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBfo0fKA/MRgCjZgK5MxxdCBkRy8OFcPWTvAoSxAFbTpPQ44+cQ+CNB9izUiSjCPotvbK4dZHCAZi+vHKR/opAHFQmhESlFrZhTOPe9eZ7pZLcJiN3bCj66DXME28yxSWv7AlvDURcneqyv4JiYzdfQYU0B++ujLMKn3XxtMUMVvYrSjwJezUOrGOvw2YLNvAjx3Bu/l+YgU6p0BVjAeEdnjYIYudjLYmJAv44Mr92+kbK6bPPF7M0fdg58pGukE24C30pyoNG0ljzfX4tIT5PHJ+aD7ihWzPJu1LMsImgSIPXe7sLJfQy3CBYqg0JBy6NNi93lUnAbxBFdWCr6WuAbej63QBadcE29h1hugF1gEjOLxAcznHol9ZH7LsUjOw8v9YXvBUsFeeIEgGEXkVGTajT/2Rlqt5IfBxWpIKSVxoBZlI30PTE/tDPq45wAmnncgzqOukm5L+jcgzWsd03zfeEhS2hf6oxicNbwT4J7SQMQsaGP6giDa4H6PoZt2s1946zUGOZV+auyM2vwb/mEyjqFJPT8eboMN87O89ofSLwMhmfq7v2th0DfLVeYh35eXSItgLsbIhfXIMTwneSQbG1jsJF59kmgQJm/cZCcQ3uFfXd9DO31lZ3tB7xhiRLqLtRozYozy2cDMTrL28qSPnUgkdStOoz+xoEu0aj7OGkr39+eQaQ4n2Ssnc6s3NU643D4PUWArfhcuyi2d4f91mMz9mlNu4am8bCBdhK1JQUKiIFbWcvS
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

